<template>
  

<section class="mt-12">
            <v-container md="7">
        <v-row justify="center">
        <v-col md="8"
            >
          
      <v-card :elevation="24">
        <v-carousel hide-delimiters dark height="500">
          <v-carousel-item
            v-for="(item,i) in items"
            :key="i"
            :src="item.src"
          ></v-carousel-item>
        </v-carousel>

            

        </v-card>


            <v-card-title class="mt-12">Project Description</v-card-title>
            <v-card-text>
              <p>
              The ICD/ITKE Research Pavilion 2014-15 demonstrates the architectural potential of a novel building method inspired by the underwater nest construction of the water spider. Through a novel robotic fabrication process an initially flexible pneumatic formwork is gradually stiffened by reinforcing it with carbon fibers from the inside. The resulting lightweight fiber composite shell forms a pavilion with unique architectural qualities, while at the same time being a highly material-efficient structure.
              </p>
              <p>
              The Institute for Computational Design (ICD) and the Institute of Building Structures and Structural Design (ITKE) continue their series of research pavilions with the new ICD/ITKE Research Pavilion 2014-15 at the University of Stuttgart. These building prototypes explore application potentials of novel computational design, simulation and fabrication processes in architecture. The pavilion was developed at the intersection of the two institute’s research fields and their collaborative teaching in the context of the interdisciplinary and international ITECH MSc program. This prototypical project is the result of one and a half years of development by researchers and students of architecture, engineering and natural sciences.
              </p>
              <p>
              The design concept is based on the study of biological construction processes for fiber-reinforced structures. These processes are relevant for applications in architecture, as they do not require complex formwork and are capable of adapting to the varying demands of the individual constructions. The biological processes form customized fiber-reinforced structures in a highly material-effective and functionally integrated way. In this respect the web building process of the diving bell water spider, (Agyroneda Aquatica) proved to be of particular interest. Thus the web construction process of water spiders was examined and the underlying behavioral patterns and design rules were analyzed, abstracted and transferred into a technological fabrication process.
              </p>
              <p>
              The water spider spends most of its life under water, for which it constructs a reinforced air bubble to survive. First, the spider builds a horizontal sheet web, under which the air bubble is placed. In a further step the air bubble is sequentially reinforced by laying a hierarchical arrangement of fibers from within. The result is a stable construct that can withstand mechanical stresses, such as changing water currents, to provide a safe and stable habitat for the spider. This natural production process shows how adaptive fabrication strategies can be utilized to create efficient fiber-reinforced structures.
              </p>
              <p>
              For the transfer of this biological formation sequence into a building construction application, a process was developed in which an industrial robot is placed within an air supported membrane envelope made of ETFE. This inflated soft shell is initially supported by air pressure, though, by robotically reinforcing the inside with carbon fiber, it is gradually stiffened into a self-supporting monocoque structure. The carbon fibers are only selectively applied where they are required for structural reinforcement, and the pneumatic formwork is simultaneously used as a functionally integrated building skin. This results in a resource efficient construction process.
              </p>
              <p>
              At the beginning of the design and construction process, the shell geometry and main fiber bundle locations are generated by a computational form finding method, which integrates fabrication constraints and structural simulation. In order to determine and adjust the fiber layouts a computational agent-based design method has been developed. Similar to the spider, a digital agent navigates the surface shell geometry generating a proposed robot path for the fiber placement. The agent behavior is derived from a variety of interrelated design parameters. This computational design process enables the designer to navigate and simultaneously integrate these design parameters into various performative fiber orientations and densities.
              </p>
              <p>
              Corresponding to the adaptive computational design strategy, a prototypical robotic fabrication process was developed for carbon fiber reinforcement on the inside of a flexible membrane. The changing stiffness of the pneumatic formwork and the resulting fluctuations in deformation during the fiber placement process pose a particular challenge to the robot control. In order to adapt to these parameters during the production process the current position and contact force is recorded via an embedded sensor system and integrated into the robot control in real time. The development of such a cyber-physical system allows constant feedback between the actual production conditions and the digital generation of robot control codes. This represents not only an important development in the context of this project, but more generally provides new opportunities for adaptive robotic construction processes.
              </p>
              <p>
              The prototypical character of the fabrication process required the development of a custom made robot tool that allows placement of carbon fibers based on integrated sensor data. The technical development of this tool became an integral part of the architectural design process. This process also posed special challenges for the material system. ETFE was identified as a suitable material for the pneumatic formwork and integrated building envelope, since it is a durable facade material and its mechanical properties minimize plastic deformation during the fiber placement. A high degree of functional integration is achieved through the use of the ETFE film as pneumatic formwork and building envelope. This saves the material consumption of conventional formwork techniques as well as an additional façade installation. A composite adhesive provided a proper bond between the ETFE film and the carbon fibers. During production nine pre-impregnated carbon fiber rovings are placed in parallel. 45km of carbon roving were laid at an average speed of 0.6 m min on 5km of robot path. This additive process not only allows stress-oriented placement of the fiber composite material, but it also minimizes the construction waste associated with typically subtractive construction processes. The ICD / ITKE Research Pavilion 2014-15 covers an area of about 40m² and an internal volume of approximately 130m³ with a span of 7.5m and a height of 4.1m. The total construction weight is just 260kg, which corresponds to a weight of 6.5kg / m².
              </p>
              <p>
              The ICD / ITKE Research Pavilion 2014-15 serves as a demonstrator for advanced computational design, simulation and manufacturing techniques and shows the innovative potential of interdisciplinary research and teaching. The prototypical building articulates the anisotropic character of the fiber composite material as an architectural quality and reflects the underlying processes in a novel texture and structure. The result is not only a particularly material-effective construction, but also an innovative and expressive architectural demonstrator.
              </p>
            </v-card-text>

  





            <v-divider class="mx-4 my-7"></v-divider>

            <v-card-title class="mb-6">Project Credits</v-card-title>

              <v-card-subtitle><b>Research Institutes</b></v-card-subtitle>
              <v-card-text>
              
              
              <a href="http://icd.uni-stuttgart.de/" target="_blank">Institute for Computational Design and Construction (ICD)</a> – Prof. Achim Menges<br>

              <a href="https://www.itke.uni-stuttgart.de/" target="_blank">Institute of Building Structures and Structural Design (ITKE)</a> – Prof. Jan Knippers
              </v-card-text>
              
              <v-card-subtitle><b>Scientific Development</b></v-card-subtitle>
              <v-card-text>
              Moritz Dörstelmann, Valentin Koslowski, Marshall Prado, Gundula Schieber, Lauren Vasey
              </v-card-text>

              <v-card-subtitle><b>System Development, Fabrication + Construction</b></v-card-subtitle>
              <v-card-text>
              <b>WiSe 2013-14, SoSe 2014, WiSe 2014-15:</b> Hassan Abbasi, Yassmin Al-Khasawneh, Yuliya Baranovskaya, Marta Besalu, Giulio Brugnaro, Elena Chiridnik, Tobias Grun, Mark Hageman, Matthias Helmreich, Julian Höll, Jessica Jorge, Yohei Kanzaki, Shim Karmin, Georgi Kazlachev, Vangel Kukov, David Leon, Kantaro Makanae, Amanda Moore, <a href="https://www.paulpoinet.com/" target="_blank">Paul Poinet</a>, Emily Scoones, Djordje Stanojevic, Andrei Stoiculescu, Kenryo Takahashi and Maria Yablonina <br>
              <b>WiSe 2014-15:</b> Rebecca Jaroszewski, Yavar Khonsari, Ondrej Kyjanek, Alberto Lago, Kuan-Ting Lai, Luigi Olivieri, Guiseppe Pultrone, Annie Scherer, Raquel Silva, Shota Tsikoliya<br>
              <b>With the support of:</b> Ehsan Baharlou, Benjamin Felbrich, Manfred Hammer, Axel Körner, Anja Mader, Michael Preisack, Seiichi Suzuki, Michael Tondera
              </v-card-text>
              <v-card-subtitle><b>Funding</b></v-card-subtitle>
              <v-card-text>
              KUKA Roboter GmbH, GETTYLAB, tat aiRstructures, SGL Carbon SE, Sika Deutschland GmbH, Daimler AG, Walther Spritz- und Lackiersysteme GmbH, Lange+Ritter GmbH, Gibbons Fan Products Ltd, igus® GmbH, Peri GmbH, HERZOG Maschinenfabrik GmbH & Co. KG, AFBW – Allianz Faserbasierter Werkstoffe Baden-Württemberg e.V., Reinhausen Plasma GmbH, Reka Klebetechnik GmbH, HECO-Schrauben GmbH & Co. KG, Airtech Europe S.A., Mack Gerüsttechnik GmbH, RentES, Stahlbau Wendeler GmbH + Co. KG, CARU Containers GmbH, EmmeShop Electronics, STILL GmbH, SH-Elektrotechnik, GEMCO, Zeppelin Rental GmbH & Co. KG
              </v-card-text>
              
              <v-container>
                <v-card
                  width="640"
                  height="298"  
                >
                <v-img
                  src="/../../../static/ICD-ITKE_RP14-15_Sponsors.jpg"
                  aspect-ratio="1"
                  class="grey lighten-2"
                  width="640"
                  height="298"
                ></v-img>
                </v-card>
              </v-container>
              

              <v-card-subtitle><b>In collaboration with</b></v-card-subtitle>
              <v-card-text>


              Departement of Evolutionary Biology of Invertebrates, University of Tuebingen – Prof. Dr. Oliver Betz<br>

              Departement of Palaeontology of Invertebrates, University of Tuebingen – Prof. Dr. James Nebelsick, Dr. Christoph Allgaier<br>

              Institute for Machine Tools, University of Stuttgart – Dr. Thomas Stehle, Rolf Bauer, Michael Reichersdörfer<br>

              Institute of Aircraft Design, University of Stuttgart – Stefan Carosella, Prof. Dr.-Ing. Peter Middendorf<br>

              </v-card-text>

              <v-card-subtitle><b>Links</b></v-card-subtitle>
                   
                   <v-btn rounded :elevation="4" class="ma-2 ml-3" href="https://www.domusweb.it/en/news/2015/07/14/icd_itke_research_pavilion.html/" target="_blank">
                   <v-icon left>mdi-arrow-right</v-icon>
                   Domus
                   </v-btn>
                   <v-btn rounded :elevation="4" class="ma-2" href="https://www.archdaily.com/770516/icd-itke-research-pavilion-2014-15-icd-itke-university-of-stuttgart/" target="_blank">
                   <v-icon left>mdi-arrow-right</v-icon>
                   ArchDaily
                   </v-btn>
                  <v-btn rounded :elevation="4" class="ma-2" href="https://www.designboom.com/architecture/icd-itke-research-pavilion-2014-15-water-spider-07-16-2015/" target="_blank">
                   <v-icon left>mdi-arrow-right</v-icon>
                   DesignBoom
                   </v-btn>                                   
                  <v-btn rounded :elevation="4" class="ma-2" href="https://www.zitronenwolf.com/rundgaenge/projekte/150626_ICD-Pavillon2015/index.php?html5=prefer/" target="_blank">
                   <v-icon left>mdi-rotate-3d</v-icon>
                  Interactive Panorama
                   </v-btn>                          

              <v-card-title class="mt-0">Project Video</v-card-title>
              <v-container>
              <v-card tile raised height="360" width="640" :elevation="24" color="black">
              <iframe         
                align="top"
                height="360"
                width="640"
                frameborder="0"
                style="border:0"
                allowfullscreen src="https://player.vimeo.com/video/132910518" allow="autoplay; fullscreen"></iframe>
             
              </v-card>
              </v-container>


              <v-card-title class="mt-10">Design Iterations</v-card-title>
              <v-card-text>
              <p>
              Design iterations for the global design of the ICD/ITKE Research Pavilion 2014/15.
              Besides the very last iterations which have been performed using Rhino Membrane (Gerry D'Anza), all of the others relied on Kangaroo (Daniel Piker).
              </p>
              </v-card-text>

              <v-container>
              <v-card tile raised height="360" width="640" :elevation="24" color="black">
              <iframe         
                align="top"
                height="360"
                width="640"
                frameborder="0"
                style="border:0"
                allowfullscreen src="https://player.vimeo.com/video/107991993" allow="autoplay; fullscreen"></iframe>
             
              </v-card>
              </v-container>
              <v-card-title class="mt-10">Project Date</v-card-title>
              <v-card-text>
                2016
              </v-card-text>
              <v-card-title>Project Location</v-card-title>
              <v-container>
              <v-card height="350" width="100%" :elevation="24">
                <iframe
                  class="map"
                  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2628.989255423891!2d9.173063715671683!3d48.782095379280086!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4799db3132ba98b1%3A0x3197c083db1757a!2sKeplerstra%C3%9Fe%2011%2C%2070174%20Stuttgart%2C%20Germany!5e0!3m2!1sen!2suk!4v1573750246687!5m2!1sen!2suk"
                  width="100%"
                  height="100%"
                  frameborder="0"
                  style="border:0"
                  allowfullscreen
                />
              </v-card>
              </v-container>
            
</v-col>



       </v-row>

      </v-container>
    </section>

    
  
</template>

<script>
  export default {
    data () {
      return {
        items: [

          {
            src: "/../../../static/ICD-ITKE_RP14-15_Image01.jpg",
          },
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Image02.jpg",
          },          
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Image10.jpg",
          },
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Image13.jpg",
          },       
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Image25.jpg",
          },
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process04.jpg",
          },
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process05.jpg",
          }, 
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process06.jpg",
          },
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process07.jpg",
          },          
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process08.jpg",
          },  
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process09.jpg",
          }, 
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process10.jpg",
          },  
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process11.jpg",
          },    
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process12.jpg",
          },  
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process13.jpg",
          },    
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process15.jpg",
          },  
          {
            src: "/../../../static/ICD-ITKE_RP14-15_Process22.jpg",
          },              
          
        ],
      }
    },
  }
</script>

<style>

</style>